export { default as Students } from './students'
export { default as Instructors } from './instructors'
export { default as Classes } from './classes'
export { default as Courses } from './courses'
export { default as Notices } from './notices'
export { default as Exams } from './exams'
export { default as Statistic } from './statistic'