export const INIT_SYSTEMSTATUS = 'INIT_SYSTEMSTATUS';
export const UPDATE_SYSTEMSTATUS = 'UPDATE_SYSTEMSTATUS';


export const SYSTEMSTATUS = {
    NON_INIT : 'NON_INIT',
    IS_INITING : 'IS_INITING',
    HAD_INIT : 'HAD_INIT',
    INIT_FAIL : 'INIT_FAIL'
}